### PR TITLE
Exception handling refactoring

### PR DESCRIPTION
**Pull request by d4rken**
I've removed the uncaught exception handler due to concerns described in #28.
I've also removed the trackException method that took arbitrary strings as arguments to discourage overusing this or abusing it. In most cases we really want to track a normal event, exceptions are not replacement for if-clauses.

We are left with a trackException method that requires a throwable object. "Custom Exception" are still very much possible just create your own Exception or use a default Exception that takes arguments in the constructor.

I also updated the documentation for the method to point out that Piwik is not a crash tracker. Additionally i mentioned possibly pitfalls from proguard interferring with event matching due to obfuscated classnames or missing linenumbers.

I also contemplated whether the trackException method is really just another helper and should be moved into the new "QuickTrack" class, it's basically a wrapper, exception it just a name for an event.
This would be in contrast to i.e. downloads which are separately tracked on Piwiks UI.

Tracker: Methods for things that are distinct within Piwik UI.
QuickTrack: Methods for things that translate stuff into generic events in the Piwik UI.

This PR doesn't move it though yet, what do you think @dotsbb ?

### CODE REVIEW

**Comment by dotsbb** [comment]
>I've removed the uncaught exception handler due to concerns described in #28.

I think we should include this feature, at least because of some users, which could wish to migrate their apps from Google analytics to Piwik SDK.
https://developer.android.com/reference/com/google/android/gms/analytics/Tracker.html#enableExceptionReporting(boolean)

**Comment by d4rken** [comment]
I'd rather we re-add it if someone really needs this. I just can not see this being useful in any but the smallest of apps, and those are usually not the apps that do heavy analytics.

Lets compromise, I've readded it as a method within QuickTrack.class and created a new PiwikExceptionHandler.class that contains all the logic separately.

What do you think about the latest commit?

I would still love for someone to create an issue, arguing for needing this in his app.
Maybe someone created an awesome Piwik server-side extension that gives it a full set of Crashtracking tools, but doesn't share it. I would be very much interested in that :smile:.
Does Google Analytics have this?

**Comment by mattab** [comment]
Once we've supported a feature, it's tricky to remove it afterwards in case some users depend on it. Also it can really be useful for some to be able to track exception (while it's far from perfect as you pointed out). 

Can you create an issue with the problems of Exception handling and few screenshots showing how it's not so useful for you yet?

**Comment by d4rken** [comment]
@mattab True, with my last commit to this PR, i added it again but in a (in my opinion) cleaner way, will have to see whether @dotsbb agrees.

I'm currently using ACRA with an app with 1000k+ active users and just now there are 1954 different types of Exceptions in the database. I pruned the database I think 2 month ago.
95% of those exceptions are bugs i can't fix.
We can split those exceptions up into different categories:
* Users screwing with the apk (Modding/Cracking etc).
* Older app versions
* Users screwing with their device ROM
* Bugs in the Android framework

Now imagine we put those 2k different exceptions into the event category of Piwik.
Unless there is a plugin i don't know about, i don't see how this can be feasonably managed within Piwik.
To organise this we would need:
* Ignore or reject exceptions from older app versions
* Mark issues as fixed
* Options to prune Exception events (by version & age)
* Sorting/Filtering by app versions / android versions

To then make the exceptions useful we would also need more information:
* App versions
* ROM details
* Full stacktraces (Crashing tracking without full stacktraces??)
(Compare with ACRA/Crashlytics)

See screenshots, now imagine packing that with 2000 different events of type "Exception" from different app versions and Android versions.
This can work for a very small app, but as soon as you are getting serious numbers, it's too chaotic. 

Piwik should focus on analytics, not try to be a crashtracker.
We can actually put that on a scale.
On the very left as pure crashtrackers we have something like ACRA.
In the middle there are hybrid solutions such as Flurry or Crashlytics.
On the right we have Piwik / GA as pure analytics.

Hm this might have came off a bit as a rant, sorry not my intention :).

**Comment by d4rken** [comment]
Maybe I'm looking at this wrong and the real use case is tracking flows like:
EntryA -> PageA ->PageB->EventC->ExceptionD
Then you could see this as page flow ending as a crash causing you to do further investigation or being able to use this information in conjunction with a real crashtracker.

It seemed to me that the functionality was being "sold" as Bugtracker/Crashtracker alternative, now I'm no longer so sure...

Did i just give myself the legit usecase i was looking for?

In any case the current PR no longer removes the functionality.

**Comment by mattab** [comment]
@d4rken it's great to read your thoughts here. Improving management and display of exceptions is in the scope  to Piwik platform. Would you mind creating an issue eg. "Piwik to measure Errors and Exceptions of apps" or similar? and copy paste there your comments... it would be great to discuss it over there

**Comment by d4rken** [comment]
@mattab 
Here? https://github.com/piwik/piwik-sdk-android/issues
Or there? https://github.com/piwik/piwik/issues

**Comment by mattab** [comment]
I meant there: https://github.com/piwik/piwik/issues :+1:

**Comment by dotsbb** [comment]
@d4rken I like your changes, but I think it's right time to merge them into dev branch. So please change the target of Your PR.

**Comment by d4rken** [comment]
@dotsbb will do.

**Pull request closed without merging**
