### PR TITLE
Gzipped dispatched json

### PR DESCRIPTION
**Pull request by eldk**
Hello,

Add support for Gzipped output when dispatches multiple events as JSON
May be set to true in initPiwik() with getTracker().setDispatchGzipped(true)
    
Need mod_deflate/APACHE or lua_zlib/NGINX (https://github.com/brimworks/lua-zlib - https://github.com/openresty/lua-nginx-module/ - https://gist.github.com/davidcaste/05b2f9461ebe4a3bb3fc) on Piwik server.

JSON posted data size is smaller from x4 to x5 compared to pure JSON post (from my test and my usage).

NGINX conf example simplified: 

`location ~ \.php$ {`
`                try_files $uri =404;`
`                access_by_lua_file /path/to/inflate.lua;`
`                fastcgi_pass unix:/path/to/php-nginx/76767768876.sock/socket;`
`        }`

inflate.lua (simplified - must check size ...)

`        local content_encoding = ngx.req.get_headers()["Content-Encoding"]`
`        local content_type = ngx.req.get_headers()["Content-Type"]`
`        if ngx.req.get_method() == "POST" and content_encoding == "gzip" and content_type ==   "application/json" then`
`        ngx.req.read_body()`
`        local gzipped_body = ngx.req.get_body_data()`
`        local inflate = require("zlib").inflate()`
`        local ungzipped_body = inflate(gzipped_body)`
`        ngx.req.set_body_data(ungzipped_body)`
`        end`

Thanks,

Eric

### CODE REVIEW

**Comment by dotsbb** [comment]
Looks very good to me :+1: 
@eldk  Can You add few words to readme?

@d4rken any objections if I merge?

**Comment by d4rken** [comment]
A unit test would be nice to have at some point, but that can also be added in another PR.
@dotsbb At some point we should clean up the readme a bit (#97) and move some stuff into the wiki.

**Comment by eldk** [comment]
Hello @d4rken ,

>A unit test would be nice to have at some point, but that can also be added in another PR.

I think that targetSDK should be previously upgrade to API 24.
I have tryed to do it, but some tests that were good with targetSDK to api 23, are breaked with API 24.
So upgrade and new test needs some refactoring.

Have you or will you try to do it ?

Thanks,

Eric

**Comment by eldk** [comment]
Hello @dotsbb 

>Can You add few words to readme?
Ok I will do it fast.

Thanks,

Eric

**Comment by d4rken** [comment]
@eldk Thanks for the info, I'll have a look.

**Comment by eldk** [comment]
Hello @dotsbb 

>Can You add few words to readme?

This is done here : https://github.com/piwik/piwik-sdk-android/pull/132

Thanks,

Eric

**Pull request merged**
