### PR TITLE
Release v0.0.4

### PR DESCRIPTION
**Pull request by d4rken**
Main change:
- Support for the custom dimensions plugin (#71)
- Replacement of the deprecated org.apache.http classes (#78)

### CODE REVIEW

**Comment by d4rken** [comment]
I think those two changes are enough to release this as v0.0.4, any objections @dotsbb ?

**Comment by dotsbb** [comment]
@d4rken no objections, just give me a few days I want to increase coverage a little bit https://coveralls.io/builds/4824628

**Comment by dotsbb** [comment]
:+1:

**Comment by d4rken** [comment]
Awesome, thanks!
Will publish on bintray then tag and merge.

**Pull request merged**
