### PR TITLE
Make it possible to supply custom dispatcher implementations

### PR DESCRIPTION
**Pull request by d4rken**
For #169

### CODE REVIEW

**Comment by d4rken** [comment]
Travis failed, but it's unrealated to this. Fix for another PR, #173

**Comment by dotsbb** [comment]
@d4rken Strange thing. I've tried to rebuild this branch on TravicCI few times and this test failed every time.

**Comment by d4rken** [comment]
I don't see how my changes would impact this test though... ?

What are your thoughts on the changes anyways.

**Comment by dotsbb** [comment]
@d4rken I like the changes. I think that there is something wrong in with following logic:
image

**Comment by d4rken** [comment]
Those changes are not part of this PR though?

I made no functional changes it's just refactoring to introduce a dispatcher interface.

**Comment by dotsbb** [comment]
@d4rken right, I compared to with `2.0` branch instead of `master`. So it makes it even more mystic.

**Comment by d4rken** [comment]
@dotsbb It was a race conditions due to the timings used to wait for events to happen.

I've extracted the code that actually sends data into an extra class with an interface that defines it. Now it's possible to use a custom implementation just to send stuff, but still use the default dispatcher and caching mechanism.

So instead of creating a custom `Dispatcher`, devs can just create a custom `PacketSender`

Also added a few unit tests that are now possible and fixed the flaky test with it.

Now I'm not sure whether I overcomplicated it...

**Comment by d4rken** [comment]
@dipendrapkrl thoughts?

**Comment by dipendrapkrl** [comment]
Looks awesome. Thank you @d4rken

**Pull request merged**
